version: '3.8'

services:
  # -----------------------------------------------------------------
  # 1. Base de Données Relationnelle (Vérité)
  # -----------------------------------------------------------------
  postgres_db:
    image: postgres:16-alpine
    container_name: oneoone_postgres
    restart: always
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oneoone_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

  # -----------------------------------------------------------------
  # 2. Base de Données In-Memory (Temps Réel / Cache)
  # -----------------------------------------------------------------
  redis_cache:
    image: redis:7-alpine
    container_name: oneoone_redis
    restart: always
    ports:
     - "6379:6379"
    # Redis utilise le port 6379 par défaut
    # Pas besoin d'ouvrir le port si seul FastAPI y accède

  # # -----------------------------------------------------------------
  # # 3. Service API (FastAPI)
  # # -----------------------------------------------------------------
  # api_service:
  #   build: . # Dockerfile dans /backend
  #   container_name: oneoone_api
  #   command: uvicorn app.api_main:app --host 0.0.0.0 --port 8000 --reload
  #   volumes:
  #     - ./backend:/app 
  #   ports:
  #     - "80000:8000"
  #   depends_on:
  #     - postgres_db # S'assure que Postgres démarre en premier
  #     - redis_cache # S'assure que Redis démarre en premier
  #   environment:
  #     # ⚠️ Mise à jour des URLs pour utiliser le nom des services (postgres_db et redis_cache)
  #     DATABASE_URL: postgresql+asyncpg://user_db:password@postgres_db:5432/oneoone_db
  #     REDIS_URL: redis://redis_cache:6379/0 # Nouvelle URL pour l'accès à Redis

# Déclaration des volumes persistants
volumes:
  postgres_data: